In [8]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [9]:
# tensor create
x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [11]:
# tensor opertion
x = torch.zeros(4, 3, dtype = torch.float32)
x = torch.randn_like(x, dtype = torch.float32)
print(x)

print(x.size())
print(x.shape)

tensor([[-1.9829,  0.3598, -0.1827],
        [-1.0489, -0.5464,  0.0797],
        [-0.2937, -0.5100, -0.0475],
        [-1.2490, -0.2409, -0.0738]])
torch.Size([4, 3])
torch.Size([4, 3])


In [12]:
# random tensor setup
a = torch.IntTensor(1,2)
b = torch.FloatTensor(2,3)
print(a, "\n", b)

tensor([[0, 0]], dtype=torch.int32) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
# tensor numpy translation
g = np.array([[1,2,3],[4,5,6]])
h = torch.tensor(g)
print(h)
i = torch.from_numpy(g)
print(i)
j = h.numpy()
print(j)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


In [14]:
# tensor view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
z2 = x.view(8, -1)
print(x.size(), "\n", y.size(), "\n", z.size(), "\n", z2.size())
# tensor operation
a = torch.ones(2, 2)
b = torch.ones(2, 2)
print(a + b)
print(a * b)
print(a / b)
print(a % b)
print(a ** b)


torch.Size([4, 4]) 
 torch.Size([16]) 
 torch.Size([2, 8]) 
 torch.Size([8, 2])
tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
